[package]
name = "brawl-game"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["client","shared", "server"]

[[bin]]
name = "server"
path = "server"

[[bin]]
name = "client"
path = "client"

